name: Container Scan
on: [push]
jobs:
  container-scan:
      runs-on: ubuntu-latest
      # needs: [ci]
      
      steps:
      - name : Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/fastapi-starter:latest'
          format: 'table'
          exit-code: '1'
